const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{stripTypeScriptTypes}=require('node:module'),crypto=require('node:crypto');
const code=fs.readFileSync(require.resolve('../supabase/functions/buytest-payment/index.ts'),'utf8').replace(/^import .*;\s*/,'');
function setup(){const ctx={Deno:{env:{get:()=>''},serve:()=>{}},TextEncoder,TextDecoder,Uint8Array,crypto:crypto.webcrypto,btoa,atob,URL,Headers,Response,Request,console};vm.createContext(ctx);vm.runInContext(stripTypeScriptTypes(code),ctx);vm.runInContext('privateConfig=async()=>"test-secret"',ctx);return ctx;}
async function scopes(plan,amount,payload={}){const c=setup();const token=await c.signedEntitlement({id:'fixture',plan,plate:'12345678',amount_agorot:amount,expires_at:new Date(Date.now()+86400000).toISOString(),provider_payload:payload});return JSON.parse(Buffer.from(token.split('.')[0],'base64url')).scopes;}
test('independent service prices agree between checkout and website',()=>{const c=setup();const html=fs.readFileSync(require.resolve('../index.html'),'utf8');for(const [plan,amount]of [['balcar',1500],['report',2900],['prebuy',7900],['consultation',7900]]){assert.equal(vm.runInContext(`PLANS.${plan}.amountAgorot`,c),amount);assert.match(html,new RegExp(plan+':\\{[^\\n]*price:'+amount/100+'[,}]'));}});
test('insurance alone and advice alone cannot unlock inspection analysis',async()=>{assert.deepEqual(await scopes('balcar',1500),['balcar']);assert.deepEqual(await scopes('prebuy',7900,{independentService:true}),['prebuy']);assert.deepEqual(await scopes('report',2900),['report']);});
test('existing package and remote advice customers keep their paid access',async()=>{assert.deepEqual(await scopes('balcar',3900),['balcar','premium','report']);assert.deepEqual(await scopes('prebuy',14900,{remoteConsultation:true}),['prebuy','consultation','balcar','premium','report']);});
test('report checkout is available independently and uses its own return page',()=>{assert.doesNotMatch(code,/\["report", "report_consultation", "premium"/);assert.match(code,/planKey === "report" \? "report"/);assert.match(code,/independentService: true/);assert.match(code,/remoteConsultation: false/);});
test('checkout and receipt line use the exact independent price and return to the chosen service',async()=>{
 for(const [plan,amount,service]of [['balcar',1500,'insurance'],['report',2900,'report'],['prebuy',7900,'consultation']]){
  const c=setup();c.created=[];c.requests=[];
  vm.runInContext(`cardcomConfig=async()=>({enabled:true,terminalNumber:1,apiName:'fixture'});insertOrder=async v=>{created.push(v);return v};updateOrder=async()=>({});cardcomRequest=async(path,body)=>{requests.push(body);return {ResponseCode:0,LowProfileId:'11111111-1111-4111-8111-111111111111',Url:'https://secure.cardcom.solutions/e/fixture'}}`,c);
  const r=await c.createPayment('https://buytest.co.il',{plan,plate:'12345678',directCheckout:true,acceptedTerms:true,independentService:true});assert.equal(r.status,200);const data=await r.json();assert.equal(data.amountAgorot,amount);assert.equal(c.created[0].amount_agorot,amount);assert.equal(c.requests[0].Amount,amount/100);assert.equal(c.requests[0].Document.Products[0].UnitCost,amount/100);assert.ok(c.requests[0].SuccessRedirectUrl.includes('?service='+service+'&buytest_payment=return'));assert.equal(c.created[0].provider_payload.remoteConsultation,false);
 }
});
test('old browser version cannot initiate checkout at a newly changed price',async()=>{const c=setup();const r=await c.createPayment('https://buytest.co.il',{plan:'balcar',plate:'12345678',directCheckout:true,acceptedTerms:true});assert.equal(r.status,409);assert.equal((await r.json()).error,'service_version_required');});
