const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {createTracker}=require('../report-funnel.js');
function setup(extra={}){const calls=[];let sessionId='session_initial_123456789';return {calls,change:()=>sessionId='session_changed_123456789',track:createTracker({identity:()=>({visitorId:'visitor_test_123456789',sessionId}),send:async b=>calls.push(b),blocked:()=>false,attribution:()=>({trafficSource:'google'}),...extra})};}
test('deduplicates repeated and concurrent interactions without inferring success',async()=>{const h=setup();await Promise.all([h.track('report_analyze_clicked'),h.track('report_analyze_clicked')]);assert.deepEqual(h.calls.map(x=>x.eventType),['report_opened','report_analyze_clicked']);});
test('async result keeps original session even after rollover',async()=>{const h=setup(),ctx=h.track.capture();await h.track('report_analysis_started',ctx);h.change();await h.track('report_result_displayed',ctx);assert.ok(h.calls.every(x=>x.sessionId===ctx.sessionId));assert.ok(h.calls.every(x=>x.vehiclePlate===null));});
test('manager and unsupported events excluded',async()=>{const h=setup({blocked:()=>true});await h.track('report_opened');assert.equal(h.calls.length,0);const h2=setup();await h2.track('fake');assert.equal(h2.calls.length,0);});
test('failed delivery retries; business error can precede success',async()=>{let n=0;const h=setup({send:async()=>{if(++n===1)throw Error('offline');}});await h.track('report_opened');await h.track('report_opened');assert.equal(n,2);const k=setup();await k.track('report_analysis_failed');await k.track('report_result_displayed');assert.equal(k.calls.length,3);});
const html=fs.readFileSync('index.html','utf8');const src=html.slice(html.indexOf('async function analyseInspectionReport(){'),html.indexOf('\nfunction openLicenseImage'));
function harness({valid=true,fail=false,mismatch=false,bad=false,postFail=false}={}){
 const events=[],el={};function node(id){return el[id]??=( {value:id==='computerTestText'?'':id==='inspectionOwnerName'?'אדם בדיקה':'טקסט לדוגמה ארוך',checked:true,disabled:false,textContent:'',classList:{add(){},remove(){}},scrollIntoView(){}});}
 let fetched=false;const track=(name)=>{events.push(name)};track.capture=()=>({});
 const c={document:{getElementById:node},plate:()=>mismatch&&fetched?'2222222':'1111111',btActivateVehicle(){},inspectionFiles:{summary:valid?{}:null,computer:[]},inspectionOcrMeta:{summary:{ok:true}},trackBuyTestReportStage:track,alert(){},storedBuyTestPayment:()=>null,buyTestManagerPin:'',callBuyTestAnalyzeService:async()=>{fetched=true;if(fail)throw Error('network');return {summary:{findings:[],unknown:[]}}},sanitizeSummaryResult:(x)=>bad?null:x,loadedKm:0,externalVehicleData:{kmHistory:[]},ocrEngineLabel:()=>'',inspectionRequesterAdvisory:()=>null,inspectionRequesterAdvisoryHtml:()=>'',escapeHtml:x=>x,professionalOverallConclusionHtml:()=>'',setClarificationFindingOptions(){},collectPreInspection:()=>({text:'',findings:[]}),btDossier:()=>({sources:{notes:true}}),btCaptureInspection(){},analysisTextBlock:()=>'',prepareReportPdf(){if(postFail)throw Error('pdf');},completeBuyTestStage:async()=>true,showFeedback(){},showClarificationOptions(){},console:{error(){}},finalizeReportFinding:x=>x};vm.createContext(c);vm.runInContext(src,c);return {events,run:()=>c.analyseInspectionReport()};
}
test('invalid input is blocked, never started or completed',async()=>{const h=harness({valid:false});await h.run();assert.deepEqual(h.events,['report_validation_blocked']);});
test('analysis failure is not a completion',async()=>{const h=harness({fail:true});await h.run();assert.deepEqual(h.events,['report_analysis_started','report_analysis_failed']);});
test('invalid response is not a completion',async()=>{const h=harness({bad:true});await h.run();assert.deepEqual(h.events,['report_analysis_started','report_analysis_failed']);});
test('changed vehicle response is discarded, never displayed',async()=>{const h=harness({mismatch:true});await h.run();assert.deepEqual(h.events,['report_analysis_started','report_result_discarded']);});
test('rendered result is recorded, later PDF failure does not undo completion',async()=>{for(const postFail of [false,true]){const h=harness({postFail});await h.run();assert.deepEqual(h.events,['report_analysis_started','report_result_received','report_result_displayed']);}});
test('all active landing copies include tracking and inline scripts parse',()=>{for(const name of ['index.html','facebook-20260928.html','facebook-final-20260928.html']){const h=fs.readFileSync(name,'utf8');assert.match(h,/report-funnel.js/);assert.match(h,/report_result_displayed/);for(const m of h.matchAll(/<script(?![^>]*src=)[^>]*>([\s\S]*?)<\/script>/g)){if(m[1].trim())new vm.Script(m[1]);}}});
