const test=require('node:test');const assert=require('node:assert/strict');
const {identity,match}=require('../vehicle-notes-core.js');
const {entries}=require('../data/vehicle-notes.json');
const record={tozeret_nm:'מזדה יפן',kinuy_mishari:'MAZDA 3',shnat_yitzur:2017,degem_manoa:'PE',sug_delek_nm:'בנזין'};
const matches=r=>entries.map(e=>match(e,identity(r))).filter(Boolean);
test('Mazda 3 identifies Hebrew maker and keeps applicability conditional',()=>{const found=matches(record);assert.equal(found.length,2);assert.ok(found.every(m=>m.uncertain));});
test('Mazda 1.5 does not inherit US 2.0/2.5 tensioner bulletin',()=>{assert.deepEqual(matches({...record,degem_manoa:'P5'}).map(m=>m.entry.id),['mazda3-wipers-19v272']);});
test('Unknown engine is marked unverified, different model/year excluded',()=>{assert.ok(matches({...record,degem_manoa:''}).every(m=>m.uncertain));assert.equal(matches({...record,kinuy_mishari:'MAZDA 6'}).length,0);assert.equal(matches({...record,shnat_yitzur:2020}).length,0);});
test('Plug-in Eclipse Cross cannot inherit CVT bulletin',()=>{assert.equal(matches({tozeret_nm:'מיצובישי',kinuy_mishari:'Eclipse Cross',shnat_yitzur:2022,sug_delek_nm:'בנזין חשמל'}).length,0);});
test('Curated records contain traceable HTTPS sources and unique IDs',()=>{assert.equal(new Set(entries.map(e=>e.id)).size,entries.length);for(const e of entries){assert.ok(new URL(e.url).protocol==='https:');for(const field of ['scope','region','description','ask','check','reviewed'])assert.ok(e[field]);}});
const vm=require('node:vm');const fs=require('node:fs');
class Element{constructor(tag){this.tag=tag;this.children=[];this.textContent='';}append(...x){this.children.push(...x);}replaceChildren(...x){this.children=x;}setAttribute(){}get text(){return this.textContent+this.children.map(c=>c.text).join(' ');}}
function harness(fetcher){const box=new Element('section');const window={BuyTestVehicleNotesCore:require('../vehicle-notes-core.js')};const context={window,document:{getElementById:()=>box,createElement:t=>new Element(t)},fetch:fetcher,AbortController,setTimeout,clearTimeout,URL,Date};vm.runInNewContext(fs.readFileSync(require.resolve('../vehicle-notes.js'),'utf8'),context);return {box,api:window.BuyTestVehicleNotes};}
test('Online outage preserves curated notes and lookup sends no plate or VIN',async()=>{let payload;const {box,api}=harness(async(url,opts)=>{if(url.startsWith('data/'))return {ok:true,json:async()=>({entries})};payload=JSON.parse(opts.body);throw Error('offline');});await api.load({...record,mispar_rechev:'1234567',misgeret:'PRIVATE'},{endpoint:'https://example.com',key:'public'});assert.deepEqual(Object.keys(payload).sort(),['make','model','year']);assert.match(box.text,/מותחן/);assert.match(box.text,/לא הושלמה/);});
test('A late response cannot overwrite a newer vehicle',async()=>{let finish;const {box,api}=harness(async(url)=>url.startsWith('data/')?{ok:true,json:async()=>({entries})}:new Promise(resolve=>finish=()=>resolve({ok:true,json:async()=>({status:'ok',items:[{id:'OLD'}],checkedAt:new Date().toISOString()})})));const first=api.load(record,{endpoint:'https://example.com',key:'public'});await api.load({tozeret_nm:'unknown',kinuy_mishari:'unknown',shnat_yitzur:2024},{endpoint:'https://example.com',key:'public'});finish();await first;assert.doesNotMatch(box.text,/OLD|מותחן/);assert.match(box.text,/אין במאגר/);});
test('Registry Megane 2020 K9K has a sourced maintenance note',()=>{const found=matches({tozeret_nm:'רנו טורקיה',kinuy_mishari:'MEGANE',shnat_yitzur:2020,degem_manoa:'K9K',sug_delek_nm:'דיזל'});assert.equal(found.length,1);assert.equal(found[0].entry.id,'renault-megane-dpf-2020');assert.equal(found[0].uncertain,true);});
test('Megane does not request an unsupported US recall lookup',async()=>{let onlineCalls=0;const {box,api}=harness(async(url)=>{if(url.startsWith('data/'))return {ok:true,json:async()=>({entries})};onlineCalls++;throw Error();});await api.load({tozeret_nm:'רנו טורקיה',kinuy_mishari:'MEGANE',shnat_yitzur:2020,degem_manoa:'K9K',sug_delek_nm:'דיזל'},{endpoint:'https://example.com',key:'public'});assert.equal(onlineCalls,0);assert.match(box.text,/מסנן חלקיקים/);assert.match(box.text,/אינו מכסה/);assert.doesNotMatch(box.text,/נשאר זמין/);});
