create table if not exists public.buytest_mileage_observations (
  id bigint generated by default as identity primary key,
  vehicle_plate text not null,
  mileage integer not null,
  source_type text not null,
  recorded_on date not null,
  date_basis text not null,
  visitor_id text,
  session_id text,
  observation_key text not null unique,
  captured_at timestamptz not null default now(),
  constraint buytest_mileage_observations_plate_check
    check (vehicle_plate ~ '^\d{7,8}$'),
  constraint buytest_mileage_observations_mileage_check
    check (mileage between 1 and 5000000),
  constraint buytest_mileage_observations_source_check
    check (source_type in ('ministry_last_test', 'inspection_report')),
  constraint buytest_mileage_observations_date_basis_check
    check (date_basis in ('test_date', 'captured_date')),
  constraint buytest_mileage_observations_visitor_check
    check (visitor_id is null or visitor_id ~ '^[A-Za-z0-9_-]{20,80}$'),
  constraint buytest_mileage_observations_session_check
    check (session_id is null or session_id ~ '^[A-Za-z0-9_-]{20,80}$'),
  constraint buytest_mileage_observations_key_check
    check (observation_key ~ '^[a-f0-9]{64}$')
);

create index if not exists buytest_mileage_observations_plate_date_idx
  on public.buytest_mileage_observations (vehicle_plate, recorded_on desc, captured_at desc);

create index if not exists buytest_mileage_observations_source_captured_idx
  on public.buytest_mileage_observations (source_type, captured_at desc);

alter table public.buytest_mileage_observations enable row level security;

revoke all on table public.buytest_mileage_observations from public, anon, authenticated;
grant select, insert on table public.buytest_mileage_observations to service_role;

revoke all on sequence public.buytest_mileage_observations_id_seq from public, anon, authenticated;
grant usage, select on sequence public.buytest_mileage_observations_id_seq to service_role;

comment on table public.buytest_mileage_observations is
  'Deduplicated mileage observations collected from Ministry of Transport lookups and user-submitted inspection reports. Report files and report text are not stored here.';
